### ISSUE TITLE
cannot import name 'SO_REUSEPORT'

### ISSUE THREAD

**Issue by zzeric** [vibora-io/vibora#106]
File "/home/abc/anaconda3/lib/python3.6/site-packages/vibora/workers/handler.py", line 3, in <module>
    from socket import IPPROTO_TCP, TCP_NODELAY, SO_REUSEADDR, SOL_SOCKET, SO_REUSEPORT,socket
ImportError: cannot import name 'SO_REUSEPORT'

python version is 3.6.0, need to upgrade to 3.7?

**Comment by rfyiamcool** [comment]
use 3.6.x

**Comment by frnkvieira** [comment]
@squeaky-pl Priceless tip, many thanks! I'll add this ASAP.

**Comment by zzeric** [comment]
@squeaky-pl thanks for reply. Yes，it's related to linux kernel and anaconda cpython compilation, it's strange about anaconda, my another centos kernel is 3.10, and the header file(/usr/include/asm-generic/socket.h) contains #define SO_REUSEPORT = 15, but anaconda python 3.6.4 still not support SO_REUSEPORT, maybe I need compile python myself.

**Comment by zzeric** [comment]
I install python 3.7.0 without anaconda，it works. But "async" get to be a reserved keyword in 3.7, I need to modify somewhere myself, advise to rename the properties named as "async"
@frnkvieira

**Comment by frnkvieira** [comment]
@zzeric this is already fixed in master branch, I'll do a release as soon as I fix the other pending issues

**Comment by danieldaeschle** [comment]
I have the same error on windows

**Comment by kdebowski** [comment]
@zzeric why did you close this issue? It's not fixed yet. @frnkvieira 's answer was related to another problem.

**Comment by hexbee** [comment]
⚠️ Confirm that the issue is not fixed on current master branch.
- Windows 10
- Python 3.6.3: Anaconda, Inc. 
- vibora 0.0.7
- Import Error :
```python
Traceback (most recent call last):
  File "runapp.py", line 1, in <module>
    from vibora import Vibora, Request
  File "D:\Program_Files\Anaconda3\lib\site-packages\vibora-0.0.7-py3.6-win-amd64.egg\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "D:\Program_Files\Anaconda3\lib\site-packages\vibora-0.0.7-py3.6-win-amd64.egg\vibora\server.py", line 10, in <module>
    from .workers.handler import RequestHandler
  File "D:\Program_Files\Anaconda3\lib\site-packages\vibora-0.0.7-py3.6-win-amd64.egg\vibora\workers\handler.py", line 3, in <module>
    from socket import IPPROTO_TCP, TCP_NODELAY, SO_REUSEADDR, SOL_SOCKET, SO_REUSEPORT, socket
ImportError: cannot import name 'SO_REUSEPORT'
```

**Comment by danieldaeschle** [comment]
According to https://stackoverflow.com/a/14388707/7301994 and https://stackoverflow.com/a/13638757/7301994 `SO_REUSEADDR` covers `SO_REUSEPORT`. We don't need `SO_REUSEPORT` at this point. I will create a PR.
